<x-storefront.account.orders.page :seo="$seo" :account="$account" :navigation="$navigation" title="Cancel Order Request" :subtitle="'Request cancellation for all or selected eligible items in '.$order->order_number.'. Cancellation is not final until approved.'" eyebrow="Order cancellation">
    <x-slot:actions><a class="btn btn-white" href="{{ route('account.orders.show',$order) }}">Order Details</a></x-slot:actions>
    <form method="POST" action="{{ route('account.orders.cancel.store',$order) }}" class="space-y-6">@csrf
        <section class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7">
            <h3 class="text-xl font-black">What would you like to cancel?</h3>
            <div class="mt-4 grid gap-4 md:grid-cols-2">
                <label class="order-choice"><input type="radio" name="scope" value="entire_order" class="peer sr-only" @checked(old('scope','entire_order')==='entire_order')><span class="block h-full rounded-2xl border border-slate-200 p-5 peer-checked:border-brand-blue peer-checked:bg-blue-50"><b class="block text-xl">Cancel entire order</b><span class="mt-2 block font-bold text-slate-500">All {{ $order->total_quantity }} items · ${{ number_format((float)$order->grand_total,2) }}</span></span></label>
                <label class="order-choice"><input type="radio" name="scope" value="selected_items" class="peer sr-only" @checked(old('scope')==='selected_items')><span class="block h-full rounded-2xl border border-slate-200 p-5 peer-checked:border-brand-blue peer-checked:bg-blue-50"><b class="block text-xl">Cancel selected items</b><span class="mt-2 block font-bold text-slate-500">Choose specific products and quantities below</span></span></label>
            </div>
        </section>
        <section class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7"><h3 class="text-xl font-black">Eligible Items</h3><div class="mt-4 grid gap-4">@foreach($order->items as $item)<div class="grid gap-3 rounded-2xl border border-slate-200 p-4 md:grid-cols-[1fr_120px]"><x-storefront.account.orders.item-row :item="$item" compact /><div><label class="admin-label">Cancel quantity</label><input class="admin-input" type="number" name="items[{{ $loop->index }}][quantity]" min="0" max="{{ $item->remainingCancellableQuantity() }}" value="0"><input type="hidden" name="items[{{ $loop->index }}][id]" value="{{ $item->id }}"></div></div>@endforeach</div></section>
        <section class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7"><div class="grid gap-4 md:grid-cols-2"><label><span class="admin-label">Reason</span><select class="admin-input" name="reason_code" required>@foreach(['ordered_by_mistake'=>'Ordered by mistake','deadline_changed'=>'Deadline changed','duplicate_order'=>'Duplicate order','payment_issue'=>'Payment issue','size_or_roster_change'=>'Size or roster change','other'=>'Other'] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><label><span class="admin-label">Additional details</span><textarea class="admin-textarea min-h-[100px]" name="reason" maxlength="1500">{{ old('reason') }}</textarea></label></div><p class="mt-4 text-sm leading-6 text-slate-500">Submitting this form creates a review request. It does not automatically cancel production, payment, or shipment.</p><button class="btn btn-red mt-5" type="submit">Submit Cancellation Request</button></section>
    </form>
</x-storefront.account.orders.page>
