<x-storefront.account.orders.page :seo="$seo" :account="$account" :navigation="$navigation" title="Change Order Request" :subtitle="'Request changes to sizes, roster, artwork, shipping, quantity, or deadlines for '.$order->order_number.' before production lock.'" eyebrow="Order changes">
    <x-slot:actions><a class="btn btn-white" href="{{ route('account.orders.show',$order) }}">Order Details</a></x-slot:actions>
    <form method="POST" action="{{ route('account.orders.change.store',$order) }}" class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7">@csrf
        <div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800"><b>Changes are reviewed before they affect production.</b> Price, delivery timing, and artwork approval may need to be recalculated.</div>
        <div class="mt-6 grid gap-5 md:grid-cols-2"><label><span class="admin-label">Change category</span><select class="admin-input" name="reason_code" required>@foreach(['sizes'=>'Sizes','roster'=>'Names or numbers','artwork'=>'Artwork or colors','shipping_address'=>'Shipping address','delivery_deadline'=>'Delivery deadline','quantity'=>'Quantity','other'=>'Other'] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><div><span class="admin-label">Affected products</span><div class="mt-2 grid gap-2">@foreach($order->items as $item)<label class="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-bold"><input type="checkbox" name="item_ids[]" value="{{ $item->id }}" class="h-4 w-4 rounded">{{ $item->product_name }}</label>@endforeach</div></div></div>
        <label class="mt-5 block"><span class="admin-label">Describe exactly what must change</span><textarea class="admin-textarea min-h-[180px]" name="requested_changes" required maxlength="3000" placeholder="List current value, requested value, sizes, names, numbers, colors, address details, and deadline information.">{{ old('requested_changes') }}</textarea></label>
        <button class="btn btn-red mt-5" type="submit">Submit Change Request</button>
    </form>
</x-storefront.account.orders.page>
