<x-storefront.account.orders.page :seo="$seo" :account="$account" :navigation="$navigation" title="Partial & Split Shipments" :subtitle="'See how products from '.$order->order_number.' are grouped across packages and delivery dates.'" eyebrow="Shipment plan">
    <x-slot:actions><a class="btn btn-white" href="{{ route('account.orders.show',$order) }}">Order Details</a></x-slot:actions>
    <div class="rounded-3xl border border-blue-200 bg-blue-50 p-5 text-sm leading-6 text-blue-800"><b>Why orders split:</b> custom products may finish at different times, ship from different facilities, or use different carriers. You are charged shipping only according to the finalized order terms.</div>
    <div class="mt-6 grid gap-5">
        @forelse($order->shipments as $shipment)
            <article class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div><p class="text-xs font-black uppercase tracking-wide text-brand-red">{{ $shipment->shipment_number }}</p><h3 class="mt-2 text-xl font-black">{{ $shipment->carrier ?: 'Carrier pending' }} {{ $shipment->service }}</h3><p class="mt-1 text-sm text-slate-500">Tracking: {{ $shipment->tracking_number ?: 'Not assigned' }} · Estimated delivery: {{ $shipment->estimated_delivery_at?->format('M d, Y') ?: 'To be confirmed' }}</p></div><x-storefront.account.orders.status-pill :status="$shipment->status" /></div><div class="mt-5 grid gap-3">@foreach($shipment->items as $shipmentItem)<div class="flex justify-between rounded-2xl bg-slate-50 p-4 text-sm"><span class="font-black">{{ $shipmentItem->orderItem->product_name }}</span><span>Qty {{ $shipmentItem->quantity }}</span></div>@endforeach</div><a class="btn btn-white mt-5" href="{{ route('account.orders.shipments.show',[$order,$shipment]) }}">View Shipment Details</a></article>
        @empty<div class="rounded-[28px] border border-slate-200 bg-white p-10 text-center shadow-card"><h3 class="text-xl font-black">Shipment plan not created yet</h3><p class="mt-2 text-sm text-slate-500">Packages will appear after production and fulfillment planning begins.</p></div>@endforelse
    </div>
</x-storefront.account.orders.page>
