@props(['item'])
@php($children=$item->childrenRecursive ?? collect())
<div class="group relative shrink-0">
    <a href="{{ $item->resolvedUrl() }}" target="{{ $item->target }}" @if($item->target==='_blank') rel="noopener noreferrer" @endif class="flex items-center gap-1 rounded-lg px-2 py-2 transition hover:bg-slate-100 hover:text-brand-red {{ $item->css_class }}">{{ $item->label }} @if($children->isNotEmpty())<span class="text-[10px]">▾</span>@endif</a>
    @if($children->isNotEmpty())
        <div class="invisible absolute left-0 top-full z-50 min-w-[620px] translate-y-2 rounded-2xl border border-slate-200 bg-white p-5 opacity-0 shadow-2xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100">
            <div class="grid grid-cols-2 gap-5 lg:grid-cols-3">@foreach($children as $child)<div><a href="{{ $child->resolvedUrl() }}" target="{{ $child->target }}" @if($child->target==='_blank') rel="noopener noreferrer" @endif class="font-black text-brand-ink hover:text-brand-red">{{ $child->label }}</a>@if($child->childrenRecursive->isNotEmpty())<ul class="mt-3 space-y-2 text-xs font-semibold text-slate-600">@foreach($child->childrenRecursive as $grandchild)<li><a href="{{ $grandchild->resolvedUrl() }}" target="{{ $grandchild->target }}" @if($grandchild->target==='_blank') rel="noopener noreferrer" @endif class="hover:text-brand-red">{{ $grandchild->label }}</a>@if($grandchild->childrenRecursive->isNotEmpty())<ul class="mt-2 space-y-1 border-l border-slate-200 pl-3 text-slate-500">@foreach($grandchild->childrenRecursive as $leaf)<li><a href="{{ $leaf->resolvedUrl() }}" target="{{ $leaf->target }}" @if($leaf->target==='_blank') rel="noopener noreferrer" @endif class="hover:text-brand-red">{{ $leaf->label }}</a></li>@endforeach</ul>@endif</li>@endforeach</ul>@endif</div>@endforeach</div>
            @if($item->category)<a href="{{ $item->resolvedUrl() }}" class="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-xs font-black uppercase tracking-wide text-brand-red"><span>View all {{ $item->label }}</span><span>→</span></a>@endif
        </div>
    @endif
</div>
