<x-storefront.account.orders.page :seo="$seo" :account="$account" :navigation="$navigation" title="Return Request" :subtitle="'Select eligible delivered items from '.$order->order_number.', explain the issue, and choose refund or store credit.'" eyebrow="Post-purchase support">
    <x-slot:actions><a class="btn btn-white" href="{{ route('account.orders.show',$order) }}">Order Details</a></x-slot:actions>
    <form method="POST" enctype="multipart/form-data" action="{{ route('account.orders.returns.store',$order) }}" class="space-y-6">@csrf
        <section class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7"><div class="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-800"><b>Eligibility is checked on the server.</b> Custom products may be non-returnable unless damaged, defective, incorrect, or otherwise covered by the store policy. Submitting a request does not guarantee approval.</div><h3 class="mt-6 text-xl font-black">Select Items</h3><div class="mt-4 grid gap-4">@foreach($order->items as $item)<div class="grid gap-4 rounded-2xl border border-slate-200 p-4 lg:grid-cols-[1fr_110px_180px]"><x-storefront.account.orders.item-row :item="$item" compact /><label><span class="admin-label">Quantity</span><input class="admin-input" type="number" name="items[{{ $loop->index }}][quantity]" min="0" max="{{ $item->returnableQuantity() }}" value="{{ old('items.'.$loop->index.'.quantity', 0) }}"><input type="hidden" name="items[{{ $loop->index }}][id]" value="{{ $item->id }}"></label><label><span class="admin-label">Condition</span><select class="admin-input" name="items[{{ $loop->index }}][condition]"><option value="unused" @selected(old('items.'.$loop->index.'.condition') === 'unused')>Unused</option><option value="opened" @selected(old('items.'.$loop->index.'.condition') === 'opened')>Opened</option><option value="worn_once" @selected(old('items.'.$loop->index.'.condition') === 'worn_once')>Worn once</option><option value="damaged" @selected(old('items.'.$loop->index.'.condition') === 'damaged')>Damaged</option></select></label></div>@endforeach</div></section>
        <section class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7"><div class="grid gap-5 md:grid-cols-2"><label><span class="admin-label">Reason</span><select class="admin-input" name="reason_code" required>@foreach(['wrong_item'=>'Wrong item received','damaged'=>'Damaged in transit','quality_issue'=>'Quality or manufacturing issue','size_issue'=>'Size issue','not_as_expected'=>'Not as expected','other'=>'Other'] as $key=>$label)<option value="{{ $key }}" @selected(old('reason_code') === $key)>{{ $label }}</option>@endforeach</select></label><label><span class="admin-label">Requested resolution</span><select class="admin-input" name="requested_resolution" required><option value="refund" @selected(old('requested_resolution', 'refund') === 'refund')>Refund to original payment method</option><option value="store_credit" @selected(old('requested_resolution') === 'store_credit')>Store credit</option></select></label></div><label class="mt-5 block"><span class="admin-label">Details</span><textarea class="admin-textarea" name="reason" maxlength="2000" placeholder="Describe the issue, affected items, and any packaging or damage details.">{{ old('reason') }}</textarea></label>
            <div class="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4">
                <label class="block"><span class="admin-label">Photo evidence <span class="font-medium normal-case text-slate-400">(optional)</span></span><input class="admin-input bg-white" type="file" name="evidence[]" multiple accept=".jpg,.jpeg,.png,.webp,.heic,.heif,image/jpeg,image/png,image/webp,image/heic,image/heif"><span class="mt-2 block text-xs leading-5 text-slate-500">Upload up to 5 clear images. Each file may be up to 5 MB. Files are stored privately and are visible only to you and authorized order staff.</span></label>
                @error('evidence')<p class="mt-2 text-sm font-bold text-red-600">{{ $message }}</p>@enderror
                @error('evidence.*')<p class="mt-2 text-sm font-bold text-red-600">{{ $message }}</p>@enderror
            </div>
            <label class="mt-5 flex items-start gap-3 rounded-2xl border border-slate-200 p-4"><input class="mt-1 h-4 w-4 rounded border-slate-300 text-brand-red focus:ring-brand-red" type="checkbox" name="confirm_accuracy" value="1" @checked(old('confirm_accuracy')) required><span class="text-sm leading-6 text-slate-600"><b class="text-brand-ink">I confirm the information is accurate.</b> I understand that approval depends on product condition, customization, delivery date, and the published return policy.</span></label>
            @error('confirm_accuracy')<p class="mt-2 text-sm font-bold text-red-600">{{ $message }}</p>@enderror
            <button class="btn btn-red mt-5" type="submit">Submit Return Request</button></section>
    </form>
</x-storefront.account.orders.page>
