<x-storefront.account.orders.page :seo="$seo" :account="$account" :navigation="$navigation" title="Exchange Request" :subtitle="'Request replacement sizes, corrected items, or approved product changes for eligible items in '.$order->order_number.'.'" eyebrow="Product exchange">
    <x-slot:actions><a class="btn btn-white" href="{{ route('account.orders.show',$order) }}">Order Details</a></x-slot:actions>
    <form method="POST" enctype="multipart/form-data" action="{{ route('account.orders.exchanges.store',$order) }}" class="space-y-6">@csrf
        <section class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7"><div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800"><b>Replacement availability and price differences require review.</b> Custom roster or artwork corrections may require a new proof before production.</div><h3 class="mt-6 text-xl font-black">Choose Items & Replacements</h3><div class="mt-4 grid gap-4">@foreach($order->items as $item)<div class="rounded-2xl border border-slate-200 p-4"><x-storefront.account.orders.item-row :item="$item" compact /><div class="mt-4 grid gap-4 md:grid-cols-3"><label><span class="admin-label">Quantity</span><input class="admin-input" type="number" name="items[{{ $loop->index }}][quantity]" min="0" max="{{ $item->returnableQuantity() }}" value="{{ old('items.'.$loop->index.'.quantity', 0) }}"><input type="hidden" name="items[{{ $loop->index }}][id]" value="{{ $item->id }}"></label><label><span class="admin-label">Condition</span><select class="admin-input" name="items[{{ $loop->index }}][condition]"><option value="unused" @selected(old('items.'.$loop->index.'.condition') === 'unused')>Unused</option><option value="opened" @selected(old('items.'.$loop->index.'.condition') === 'opened')>Opened</option><option value="worn_once" @selected(old('items.'.$loop->index.'.condition') === 'worn_once')>Worn once</option><option value="damaged" @selected(old('items.'.$loop->index.'.condition') === 'damaged')>Damaged</option></select></label><label><span class="admin-label">Replacement requested</span><input class="admin-input" name="items[{{ $loop->index }}][replacement]" maxlength="800" placeholder="Example: Adult L instead of M" value="{{ old('items.'.$loop->index.'.replacement') }}"></label></div></div>@endforeach</div></section>
        <section class="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card md:p-7"><label><span class="admin-label">Exchange reason</span><select class="admin-input" name="reason_code" required>@foreach(['size_issue'=>'Size issue','wrong_item'=>'Wrong item received','defective'=>'Defective product','roster_correction'=>'Roster correction','other'=>'Other'] as $key=>$label)<option value="{{ $key }}" @selected(old('reason_code') === $key)>{{ $label }}</option>@endforeach</select></label><label class="mt-5 block"><span class="admin-label">Exchange instructions</span><textarea class="admin-textarea min-h-[160px]" name="exchange_notes" required maxlength="2500" placeholder="Explain the required replacement sizes, names, numbers, colors, or correction details.">{{ old('exchange_notes') }}</textarea></label>
            <div class="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4">
                <label class="block"><span class="admin-label">Photo evidence <span class="font-medium normal-case text-slate-400">(optional)</span></span><input class="admin-input bg-white" type="file" name="evidence[]" multiple accept=".jpg,.jpeg,.png,.webp,.heic,.heif,image/jpeg,image/png,image/webp,image/heic,image/heif"><span class="mt-2 block text-xs leading-5 text-slate-500">Upload up to 5 clear images. Each file may be up to 5 MB. Files are stored privately and are visible only to you and authorized order staff.</span></label>
                @error('evidence')<p class="mt-2 text-sm font-bold text-red-600">{{ $message }}</p>@enderror
                @error('evidence.*')<p class="mt-2 text-sm font-bold text-red-600">{{ $message }}</p>@enderror
            </div>
            <label class="mt-5 flex items-start gap-3 rounded-2xl border border-slate-200 p-4"><input class="mt-1 h-4 w-4 rounded border-slate-300 text-brand-red focus:ring-brand-red" type="checkbox" name="confirm_timeline" value="1" @checked(old('confirm_timeline')) required><span class="text-sm leading-6 text-slate-600"><b class="text-brand-ink">I understand the exchange timeline.</b> Replacement production or shipment begins only after eligibility, availability, artwork, and any price difference are confirmed.</span></label>
            @error('confirm_timeline')<p class="mt-2 text-sm font-bold text-red-600">{{ $message }}</p>@enderror
            <button class="btn btn-red mt-5" type="submit">Submit Exchange Request</button></section>
    </form>
</x-storefront.account.orders.page>
