<?php

$root = dirname(__DIR__, 2);
$cssPath = $root.'/resources/css/storefront.css';
$tailwindPath = $root.'/tailwind.config.js';
$css = (string) file_get_contents($cssPath);
$tailwind = (string) file_get_contents($tailwindPath);

$failures = [];

// These utility names are generated by Tailwind and are also used by @apply
// elsewhere in storefront.css. Re-declaring them as product-page CSS rules
// makes Tailwind resolve @apply against the custom rule and creates a cycle.
foreach ([
    'text-brand-ink',
    'text-brand-blue',
    'text-brand-red',
    'border-brand-blue',
    'border-brand-red',
    'bg-brand-blue',
    'bg-brand-red',
    'ring-brand-red',
] as $utility) {
    if (preg_match('/\.np-product-page\s+\.'.preg_quote($utility, '/').'\b/', $css)) {
        $failures[] = "product-detail CSS redeclares Tailwind utility .{$utility}";
    }
}


$productDetailThemeSources = [
    'resources/views/storefront/products/show.blade.php',
    'resources/views/components/storefront/product/builder.blade.php',
    'resources/views/components/storefront/product/gallery.blade.php',
    'resources/views/components/storefront/product/details.blade.php',
    'resources/views/components/storefront/product/purchase-signals.blade.php',
    'resources/views/components/storefront/product/option-group.blade.php',
];

foreach ($productDetailThemeSources as $relativePath) {
    $contents = (string) file_get_contents($root.'/'.$relativePath);
    if (preg_match('/(?:bg|text|border|ring|hover:bg|hover:text|focus:ring|focus:border)-(?:red|blue|cyan|indigo)-[0-9]+(?:\/[0-9]+)?/', $contents, $match)) {
        $failures[] = "product-detail source {$relativePath} uses non-central palette utility {$match[0]}";
    }
}

foreach ([
    "blue: themeColor('--np-color-primary')",
    "red: themeColor('--np-color-secondary')",
    "ink: themeColor('--np-color-heading')",
] as $mapping) {
    if (! str_contains($tailwind, $mapping)) {
        $failures[] = "centralized Tailwind mapping missing: {$mapping}";
    }
}

if ($failures !== []) {
    fwrite(STDERR, "Product detail Tailwind build guard failed:\n - ".implode("\n - ", $failures)."\n");
    exit(1);
}

echo "Product detail Tailwind build guard passed.\n";
