<?php

return [
    'return_window_days' => (int) env('COMMERCE_RETURN_WINDOW_DAYS', 30),
    'exchange_window_days' => (int) env('COMMERCE_EXCHANGE_WINDOW_DAYS', 30),
    'cancellable_statuses' => ['pending_payment', 'payment_review', 'design_review'],
    'changeable_statuses' => ['pending_payment', 'payment_review', 'design_review'],
    'payable_statuses' => ['pending_payment', 'payment_review', 'payment_failed', 'quote_invoice_requested'],
    'order_statuses' => [
        'pending_payment' => 'Pending Payment',
        'payment_review' => 'Payment Review',
        'payment_failed' => 'Payment Failed',
        'design_review' => 'Design Review',
        'proof_approval' => 'Proof Approval',
        'in_production' => 'In Production',
        'partially_shipped' => 'Partially Shipped',
        'shipped' => 'Shipped',
        'delivered' => 'Delivered',
        'completed' => 'Completed',
        'cancelled' => 'Cancelled',
        'on_hold' => 'On Hold',
        'quote_invoice_requested' => 'Invoice Requested',
    ],
    'payment_statuses' => [
        'pending' => 'Pending',
        'processing' => 'Processing',
        'paid' => 'Paid',
        'failed' => 'Failed',
        'partially_refunded' => 'Partially Refunded',
        'refunded' => 'Refunded',
    ],
    'fulfillment_statuses' => [
        'unfulfilled' => 'Unfulfilled',
        'partial' => 'Partially Fulfilled',
        'fulfilled' => 'Fulfilled',
        'returned' => 'Returned',
    ],
    'shipment_statuses' => [
        'preparing' => 'Preparing',
        'label_created' => 'Label Created',
        'in_transit' => 'In Transit',
        'out_for_delivery' => 'Out for Delivery',
        'delivered' => 'Delivered',
        'exception' => 'Exception',
    ],
    'shipment_status_transitions' => [
        'preparing' => ['preparing', 'label_created', 'in_transit', 'exception'],
        'label_created' => ['label_created', 'in_transit', 'exception'],
        'in_transit' => ['in_transit', 'out_for_delivery', 'delivered', 'exception'],
        'out_for_delivery' => ['out_for_delivery', 'in_transit', 'delivered', 'exception'],
        'exception' => ['exception', 'in_transit', 'out_for_delivery', 'delivered'],
        'delivered' => ['delivered'],
    ],
    'change_request_statuses' => [
        'pending' => 'Pending',
        'approved' => 'Approved',
        'rejected' => 'Rejected',
        'completed' => 'Completed',
    ],
    'return_statuses' => [
        'requested' => 'Requested',
        'under_review' => 'Under Review',
        'approved' => 'Approved',
        'label_issued' => 'Label Issued',
        'in_transit' => 'In Transit',
        'received' => 'Received',
        'completed' => 'Completed',
        'rejected' => 'Rejected',
        'cancelled' => 'Cancelled',
    ],
    'return_status_transitions' => [
        'requested' => ['requested', 'under_review', 'approved', 'rejected', 'cancelled'],
        'under_review' => ['under_review', 'approved', 'rejected', 'cancelled'],
        'approved' => ['approved', 'label_issued', 'in_transit', 'received', 'completed', 'cancelled'],
        'label_issued' => ['label_issued', 'in_transit', 'received', 'completed'],
        'in_transit' => ['in_transit', 'received'],
        'received' => ['received', 'completed'],
        'completed' => ['completed'],
        'rejected' => ['rejected'],
        'cancelled' => ['cancelled'],
    ],
    'refund_statuses' => [
        'pending' => 'Pending',
        'processing' => 'Processing',
        'issued' => 'Issued',
        'failed' => 'Failed',
        'cancelled' => 'Cancelled',
    ],
];
