<x-layouts.admin title="Orders">
    <form method="GET" class="mb-6 grid gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-card lg:grid-cols-[1fr_220px_220px_auto]">
        <input class="admin-input mt-0" name="q" value="{{ request('q') }}" placeholder="Order number, customer, or email">
        <select class="admin-input mt-0" name="status"><option value="">All statuses</option>@foreach($orderStatuses as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select>
        <select class="admin-input mt-0" name="payment_status"><option value="">All payments</option>@foreach($paymentStatuses as $key=>$label)<option value="{{ $key }}" @selected(request('payment_status')===$key)>{{ $label }}</option>@endforeach</select>
        <button class="btn btn-red" type="submit">Filter</button>
    </form>

    <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-card">
        <div class="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center"><div><h2 class="text-xl font-black">Customer Orders</h2><p class="text-sm text-slate-500">Payment, production, fulfillment, returns, refunds, documents, and notes.</p></div><a class="btn btn-white" href="{{ route('admin.returns.index') }}">Returns & Exchanges</a></div>
        <div class="touch-scroll-x" tabindex="0" aria-label="Customer orders table"><table class="admin-table min-w-[900px] text-sm"><thead class="bg-slate-50 text-left text-[10px] uppercase tracking-[.12em] text-slate-500"><tr><th class="px-5 py-3">Order</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Payment</th><th class="px-5 py-3">Fulfillment</th><th class="px-5 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($orders as $order)<tr class="hover:bg-slate-50"><td class="px-5 py-4"><a class="font-black text-brand-blue" href="{{ route('admin.orders.show',$order) }}">{{ $order->order_number }}</a><p class="text-xs text-slate-400">{{ $order->placed_at?->format('M d, Y · g:i A') }}</p></td><td class="px-5 py-4"><p class="font-black">{{ $order->customer_name }}</p><p class="text-xs text-slate-500">{{ $order->customer_email }}</p></td><td class="px-5 py-4"><x-storefront.account.orders.status-pill :status="$order->status" /></td><td class="px-5 py-4"><x-storefront.account.orders.status-pill :status="$order->payment_status" /></td><td class="px-5 py-4">{{ $order->fulfillmentStatusLabel() }}</td><td class="px-5 py-4 text-right font-black">${{ number_format((float)$order->grand_total,2) }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-slate-500">No orders found.</td></tr>@endforelse</tbody></table></div>
    </section>
    <div class="mt-6">{{ $orders->links() }}</div>
</x-layouts.admin>
